### ISSUE TITLE
couldn't find an OpenGL ES implementation

### ISSUE THREAD

**Issue by nim1z** [sirahuu/android_device_sanyo_40TL04#1]
この"marshmallow"ブランチで、android-4.4.4_r2.0.1（AOSP）の "make" に成功し、起動したものの
>I/SurfaceFlinger( 1985): SurfaceFlinger is starting
I/SurfaceFlinger( 1985): SurfaceFlinger's main thread ready to run. Initializing graphics H/W...
F/libEGL ( 1985): couldn't find an OpenGL ES implementation
F/libc ( 1985): Fatal signal 6 (SIGABRT) at 0x000007c1 (code=-6), thread 1985 (surfaceflinger)

というエラーが起きます。
また、

>/system/lib/egl/
    libEGL_imx51.so
    libGLESv1_CM_imx51.so
    libGLESv2_imx51.so
/syste/lib/
    libgsl_fsl.so
    libc2d_z160.so
    libc2d_z430.so 

を、純正の Android 2.3.7 から移すと、Segfaults が起きました。
カーネル（uImage）は以下のものをビルドして使いました。
https://github.com/Mirenk/android_kernel_sanyo_imx53/tree/android-2.3.7_r1
どうすれば解決できますか。
また、カーネルバージョンが異なるものですが、以下のサイトは見つけました。
https://powerdeveloper.org/forums/viewtopic.php?f=2&t=2228

**Comment by sirahuu** [comment]
どこかに ”libGLES_android.so” を生成するフラグがあるのでそれを有効にしてビルドしてください。ライブラリは基本的にバージョンが変わると使えません。
また、それでもだめな場合は /frameworks/native/services/surfaceflinger/SurfaceFlinger.cpp の528行目あたりの "// If ES2 fails, try ES1" の前のif条件式から "// print some debugging info" の前までコメントアウトしてみてください。
さらにそれでもだめなら、ディバイスツリー内のopenglのディレクトリにあるファイルがビルドされているかと、ハードウェアレンダラーが無効になっているかを確認してください。

**Comment by nim1z** [comment]
device.mk には
>PRODUCT_PACKAGES := \
        libasound\
        make_ext4fs \
	com.android.future.usb.accessory \
	librs_jni \
        libGLES_android

すでに記述されてあります。
しかし ICS 以降の Android ではハードウェアレンダラーが必須のような情報がみつかっています。

ちなみに、ビルド後 libGLES_android.so は存在せず、同名のライブラリを勝手に配置しても無視されました（読みこんでくれない、前述の〜imx51.so を置くと読みに行ってSEGVになる）

**Comment by sirahuu** [comment]
別にハードウェアレンダリングは必須ではないです。あるに越したことはないけれども、そのへんはソースがないので今の所いじれません。それに本当に必須ならエミュレータは動きませんから…。

もしも本当に libGLES_android.so が生成されないのなら、部分生成で強制的に作ってください。

**Comment by nim1z** [comment]
失礼しました。
ありがとうございました。

**Comment by nim1z** [comment]
（一旦Issueを閉じてしまいましたが送ります、すみません。）
libGLES_android.so は生成されていましたが、やっぱり surfaceflinger は起動しませんでした。
https://gist.github.com/nim1z/e30000b45f4b85999446b2c958caa5d6

**Comment by sirahuu** [comment]
改めて内容を読んでみたら、"marshmallow" のブランチを使っているようですが、"kitkat" ブランチのほうは見ましたか？
"couldn't find an OpenGL ES implementation" というエラーはそもそも "libGLES_android.so" を読みに行ってすらいません。

**Comment by nim1z** [comment]
kikatのほうはビルドが通りませんでした…
一応通した時のは以下になります
https://github.com/nim1z/android_device_sanyo_bej2

**Comment by sirahuu** [comment]
https://github.com/sirahuu/android_device_sanyo_40TL04/tree/kitkat

**Comment by sirahuu** [comment]
"couldn't find an OpenGL ES implementation" が出たならopenglのディテクトリをaospのソースに上書きしてみてください。

**Comment by nim1z** [comment]
試しに、ビルド後の libGLES_android.so を libGLES_imx51.so にリネームしたら、一応 bootanimation が表示されました（表示が点滅してしまっていますが）

**Comment by sirahuu** [comment]
ソフトウェアレンダリングなので点滅するのは今の所解決策はないですね…。

**Comment by nim1z** [comment]
リネームという無理矢理な方法ですが、bootanimation も終わり、表示そのものは動いたのでここは閉じます。ありがとうございました。
